cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerence/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("account/", include("account.urls")),
    path('admin/', admin.site.urls),
    path('', include("product.urls")),
    path('', include("cart.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

product/urls.py
import patterns as patterns
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ShowView.as_view(), name='show'),
    path('details/<int:id>', views.DetailsView.as_view(), name='details'),
    # path('checkout_cart', views.signin, name='account_login'),
    # path('logout/', views.signout, name='account_logout'),
    # path('signup/', views.signup, name='account_signup'),
    # url(r'^accounts/login$', 'django.contrib.auth.views.login'),
]


cart/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models


class Categories(models.Model):
    category_name = models.CharField(max_length=50)

    def __str__(self):
        return "{}".format(self.category_name)


class Product(models.Model):
    product_name = models.CharField(max_length=50)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.product_name)


class ProductDetails(models.Model):
    price = models.DecimalField(max_digits=10, decimal_places=2)
    color = models.CharField(max_length=20)
    warranty = models.CharField(max_length=20)
    weightAndDimension = models.TextField(max_length=220)
    display = models.TextField(max_length=220)
    chip = models.TextField(max_length=120)
    iSightCamera = models.TextField(max_length=220)
    vedioRecording = models.TextField(max_length=220)
    quantity = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="productDetail")

    def __str__(self):
        return "{}".format(self.product.product_name)


class Specifications(models.Model):
    specification = models.TextField(max_length=120)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.product.product_name)


class Description(models.Model):
    FeatureName = models.CharField(max_length=50)
    Description = models.TextField(max_length=220)
    Image = models.FileField(max_length=100, upload_to='Images/')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.product.product_name)


class Images(models.Model):
    Images = models.FileField(max_length=100, upload_to='Images/')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.product.product_name)


class Capacity(models.Model):
    Capacity = models.CharField(max_length=20)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.Capacity)


class Credentials(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=100)
    email = models.CharField(max_length=120)

    def __str__(self):
        return "{}".format(self.username)

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

product/forms.py
from django import forms
from .models import Credentials
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# class SignupForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username', 'email', 'password1', 'password2']


# class SigninForm(forms.Form):
#     username = forms.CharField()
#     password = forms.CharField(widget=forms.PasswordInput)


cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from product.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product)
        # cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return render(request, 'cart/detail.html', {'cart': cart})


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    # for item in cart:
    #     item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

product/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from cart.forms import CartAddProductForm
from .forms import *
from django.contrib.auth.models import User
from product.utils import get_ecommerence_context_data
from .models import *


class ShowView(View):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        context = get_ecommerence_context_data()
        return render(request, self.template_name, context)


class DetailsView(LoginRequiredMixin, View):
    permission_required = ''
    template_name = 'product_details.html'

    def get(self, request, id):
        # product = Product.objects.get(id=id)
        detail_images = Images.objects.filter(product_id=id)
        main_img = Images.objects.filter(product_id=id).first()
        details = ProductDetails.objects.get(product_id=id)
        specs = Specifications.objects.filter(product_id=id)
        desc = Description.objects.filter(product_id=id)
        cap = Capacity.objects.filter(product_id=id)
        context = get_ecommerence_context_data()
        # context['pro'] = product
        context['detail_images'] = detail_images
        context['main_img'] = main_img
        context['details'] = details
        context['specs'] = specs
        context['desc'] = desc
        context['cap'] = cap
        context['product_id'] = id
        context['cart_product_form'] = CartAddProductForm()
        return render(request, self.template_name, context)

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% block header %}
        {% include '_header.html' %}
    {% endblock header %}
{% block content %}
<div class="section-container" id="checkout-cart">
            <!-- BEGIN container -->
            <div class="container">
                <!-- BEGIN checkout -->
                <div class="checkout">
                    <form action="checkout_info.html" method="POST" name="form_checkout">
                        <!-- BEGIN checkout-header -->
                        <div class="checkout-header">
                            <!-- BEGIN row -->
                            <div class="row">
                                <!-- BEGIN col-3 -->
                                <div class="col-md-3 col-sm-3">
                                    <div class="step active">
                                        <a href="#">
                                            <div class="number">1</div>
                                            <div class="info">
                                                <div class="title">Delivery Options</div>
                                                <div class="desc">Lorem ipsum dolor sit amet.</div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <!-- END col-3 -->
                                <!-- BEGIN col-3 -->
                                <div class="col-md-3 col-sm-3">
                                    <div class="step">
                                        <a href="checkout_info.html">
                                            <div class="number">2</div>
                                            <div class="info">
                                                <div class="title">Shipping Address</div>
                                                <div class="desc">Vivamus eleifend euismod.</div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <!-- END col-3 -->
                                <!-- BEGIN col-3 -->
                                <div class="col-md-3 col-sm-3">
                                    <div class="step">
                                        <a href="checkout_payment.html">
                                            <div class="number">3</div>
                                            <div class="info">
                                                <div class="title">Payment</div>
                                                <div class="desc">Aenean ut pretium ipsum. </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <!-- END col-3 -->
                                <!-- BEGIN col-3 -->
                                <div class="col-md-3 col-sm-3">
                                    <div class="step">
                                        <a href="checkout_complete.html">
                                            <div class="number">4</div>
                                            <div class="info">
                                                <div class="title">Complete Payment</div>
                                                <div class="desc">Curabitur interdum libero.</div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <!-- END col-3 -->
                            </div>
                            <!-- END row -->
                        </div>
                        <!-- END checkout-header -->
                        <!-- BEGIN checkout-body -->
                        <div class="checkout-body">
                            <div class="table-responsive">
                                <table class="table table-cart">
                                    <thead>
                                        <tr>
                                            <th>Product Name</th>
                                            <th class="text-center">Price</th>
                                            <th class="text-center">Quantity</th>
                                            <th class="text-center">Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for product in cart %}
                                        <tr>
                                            <td class="cart-product">
                                                <div class="product-img">
                                                    <img src="assets/img/iphone-6s-plus.png" alt="" />
                                                </div>
                                                <div class="product-info">

                                                    <div class="title">{{ product.product_name }}</div>
                                                    <div class="desc">Delivers Tue 26/04/2016 - Free</div>
                                                </div>
                                            </td>
                                            <td class="cart-price text-center">$999.00</td>
                                            <td class="cart-qty text-center">
                                                <div class="cart-qty-input">
                                                    <a href="#" class="qty-control left disabled" data-click="decrease-qty" data-target="#qty"><i class="fa fa-minus"></i></a>
                                                    <input type="text" name="qty" value="1" class="form-control" id="qty" />
                                                    <a href="#" class="qty-control right disabled" data-click="increase-qty" data-target="#qty"><i class="fa fa-plus"></i></a>
                                                </div>
                                                <div class="qty-desc">1 to max order</div>
                                            </td>
                                            <td class="cart-total text-center">
                                                $999.00
                                            </td>
                                        </tr>
                                    {% endfor %}
                                        <tr>
                                            <td class="cart-summary" colspan="4">
                                                <div class="summary-container">
                                                    <div class="summary-row">
                                                        <div class="field">Cart Subtotal</div>
                                                        <div class="value">$999.00</div>
                                                    </div>
                                                    <div class="summary-row text-danger">
                                                        <div class="field">Free Shipping</div>
                                                        <div class="value">$0.00</div>
                                                    </div>
                                                    <div class="summary-row total">
                                                        <div class="field">Total</div>
                                                        <div class="value">$999.00</div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- END checkout-body -->
                        <!-- BEGIN checkout-footer -->
                        <div class="checkout-footer">
                            <a href="#" class="btn btn-white btn-lg pull-left">Continue Shopping</a>
                            <button type="submit" class="btn btn-inverse btn-lg p-l-30 p-r-30 m-l-10">Checkout</button>
                        </div>
                        <!-- END checkout-footer -->
                    </form>
                </div>
                <!-- END checkout -->
            </div>
            <!-- END container -->
        </div>
        <!-- END #checkout-cart -->

        <!-- BEGIN #policy -->
        <div id="policy" class="section-container p-t-30 p-b-30 bg-white">
            <!-- BEGIN container -->
            <div class="container">
                <!-- BEGIN row -->
                <div class="row">
                    <!-- BEGIN col-4 -->
                    <div class="col-md-4 col-sm-4">
                        <!-- BEGIN policy -->
                        <div class="policy">
                            <div class="policy-icon"><i class="fa fa-truck"></i></div>
                            <div class="policy-info">
                                <h4>Free Delivery Over $100</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            </div>
                        </div>
                        <!-- END policy -->
                    </div>
                    <!-- END col-4 -->
                    <!-- BEGIN col-4 -->
                    <div class="col-md-4 col-sm-4">
                        <!-- BEGIN policy -->
                        <div class="policy">
                            <div class="policy-icon"><i class="fa fa-shield"></i></div>
                            <div class="policy-info">
                                <h4>1 Year Warranty For Phones</h4>
                                <p>Cras laoreet urna id dui malesuada gravida. <br />Duis a lobortis dui.</p>
                            </div>
                        </div>
                        <!-- END policy -->
                    </div>
                    <!-- END col-4 -->
                    <!-- BEGIN col-4 -->
                    <div class="col-md-4 col-sm-4">
                        <!-- BEGIN policy -->
                        <div class="policy">
                            <div class="policy-icon"><i class="fa fa-user-md"></i></div>
                            <div class="policy-info">
                                <h4>6 Month Warranty For Accessories</h4>
                                <p>Fusce ut euismod orci. Morbi auctor, sapien non eleifend iaculis.</p>
                            </div>
                        </div>
                        <!-- END policy -->
                    </div>
                    <!-- END col-4 -->
                </div>
                <!-- END row -->
            </div>
            <!-- END container -->
        </div>
        <!-- END #policy -->
{% endblock %}
{% block footer %}
        {% include '_footer.html' %}
    {% endblock %}

product/templates/_footer.html
<div id="footer" class="footer">
            <!-- BEGIN container -->
            <div class="container">
                <!-- BEGIN row -->
                <div class="row">
                    <!-- BEGIN col-3 -->
                    <div class="col-md-3">
                        <h4 class="footer-header">ABOUT US</h4>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec tristique dolor, ac efficitur velit. Nulla lobortis tempus convallis. Nulla aliquam lectus eu porta pulvinar. Mauris semper justo erat.
                        </p>
                        <p>
                            Vestibulum porttitor lorem et vestibulum pharetra. Phasellus sit amet mi congue, hendrerit mi ut, dignissim eros.
                        </p>
                    </div>
                    <!-- END col-3 -->
                    <!-- BEGIN col-3 -->
                    <div class="col-md-3">
                        <h4 class="footer-header">RELATED LINKS</h4>
                        <ul class="fa-ul">
                            <li><i class="fa fa-li fa-angle-right"></i> <a href="#">Shopping Help</a></li>
                            <li><i class="fa fa-li fa-angle-right"></i> <a href="#">Terms of Use</a></li>
                            <li><i class="fa fa-li fa-angle-right"></i> <a href="#">Contact Us</a></li>
                            <li><i class="fa fa-li fa-angle-right"></i> <a href="#">Careers</a></li>
                            <li><i class="fa fa-li fa-angle-right"></i> <a href="#">Payment Method</a></li>
                            <li><i class="fa fa-li fa-angle-right"></i> <a href="#">Sales & Refund</a></li>
                            <li><i class="fa fa-li fa-angle-right"></i> <a href="#">Sitemap</a></li>
                            <li><i class="fa fa-li fa-angle-right"></i> <a href="#">Privacy & Policy</a></li>
                        </ul>
                    </div>
                    <!-- END col-3 -->
                    <!-- BEGIN col-3 -->
                    <div class="col-md-3">
                        <h4 class="footer-header">LATEST PRODUCT</h4>
                        <ul class="list-unstyled list-product">
                            {% for detail in productDetails %}
                            <li>
                                <div class="image">
                                    <img src="{{ detail.product.images_set.first.Images.url }}" alt="" />
                                </div>
                                <div class="info">
                                    <h4 class="info-title">{{ detail.product.product_name }}</h4>
                                    <div class="price">{{ detail.price }}</div>

                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- END col-3 -->
                    <!-- BEGIN col-3 -->
                    <div class="col-md-3">
                        <h4 class="footer-header">OUR CONTACT</h4>
                        <address>
                            <strong>Twitter, Inc.</strong><br />
                            1355 Market Street, Suite 900<br />
                            San Francisco, CA 94103<br /><br />
                            <abbr title="Phone">Phone:</abbr> (123) 456-7890<br />
                            <abbr title="Fax">Fax:</abbr> (123) 456-7891<br />
                            <abbr title="Email">Email:</abbr> <a href="mailto:sales@myshop.com">sales@myshop.com</a><br />
                            <abbr title="Skype">Skype:</abbr> <a href="skype:myshop">myshop</a>
                        </address>
                    </div>
                    <!-- END col-3 -->
                </div>
                <!-- END row -->
            </div>
            <!-- END container -->
        </div>

product/templates/account_base.html
{% load staticfiles %}
<title>
{%block title%}{% endblock %}
</title>
<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet"/>
    <link href="{% static "assets/plugins/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet"/>
    <link href="{% static "assets/plugins/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet"/>
    <link href="{% static "assets/css/style.min.css" %}" rel="stylesheet"/>
    <link href="{% static "assets/css/style-responsive.min.css" %}" rel="stylesheet"/>
    <link href="{% static "assets/css/theme/default.css" %}" id="theme" rel="stylesheet"/>
    <link href="{% static "assets/css/animate.min.css" %}" rel="stylesheet"/>
{% block content %} {% endblock content %}
{% block js%} {% endblock js%}

product/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8"/>
    <title>
        {% block title %}
            E-Commerce Front End Theme
        {% endblock title %}
    </title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>

    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet"/>
    <link href="{% static "assets/plugins/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet"/>
    <link href="{% static "assets/plugins/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet"/>
    <link href="{% static "assets/css/style.min.css" %}" rel="stylesheet"/>
    <link href="{% static "assets/css/style-responsive.min.css" %}" rel="stylesheet"/>
    <link href="{% static "assets/css/theme/default.css" %}" id="theme" rel="stylesheet"/>
    <link href="{% static "assets/css/animate.min.css" %}" rel="stylesheet"/>
    <!-- ================== END BASE CSS STYLE ================== -->

    <!-- ================== BEGIN BASE JS ================== -->
    <script src="{% static "assets/plugins/pace/pace.min.js" %}"></script>
    <!-- ================== END BASE JS ================== -->
</head>
<body>
<!-- BEGIN #page-container -->
<div id="page-container" class="fade">
    <!-- BEGIN #top-nav -->
    <div id="top-nav" class="top-nav">
        <!-- BEGIN container -->
        <div class="container">
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown dropdown-hover">
                        <a href="#" data-toggle="dropdown"><img src="assets/img/english.png" class="flag-img" alt=""/>
                            English <i class="fa fa-angle-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><img src="{% static "assets/img/english.png" %}" class="flag-img" alt=""/>
                                English</a></li>
                            <li><a href="#"><img src="{% static "assets/img/german.png" %}" class="flag-img" alt=""/>
                                German</a></li>
                            <li><a href="#"><img src="{% static "assets/img/spanish.png" %}" class="flag-img" alt=""/>
                                Spanish</a></li>
                            <li><a href="#"><img src="{% static "assets/img/french.png" %}" class="flag-img" alt=""/>
                                French</a></li>
                            <li><a href="#"><img src="{% static "assets/img/chinese.png" %}" class="flag-img" alt=""/>
                                Chinese</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Customer Care</a></li>
                    <li><a href="#">Order Tracker</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Career</a></li>
                    <li><a href="#">Our Forum</a></li>
                    <li><a href="#">Newsletter</a></li>
                    <li><a href="#"><i class="fa fa-facebook f-s-14"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter f-s-14"></i></a></li>
                    <li><a href="#"><i class="fa fa-instagram f-s-14"></i></a></li>
                    <li><a href="#"><i class="fa fa-dribbble f-s-14"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus f-s-14"></i></a></li>
                </ul>
            </div>
        </div>
        <!-- END container -->
    </div>
    <!-- END #top-nav -->

    <!-- BEGIN #header -->

    <!-- END #header -->

    {% block header %}
        {% include '_header.html' %}
    {% endblock header %}
    {% block content %}

    {% endblock content %}
    <!-- BEGIN #footer -->
    {% block footer %}
        {% include '_footer.html' %}
    {% endblock %}
    <!-- END #footer -->

    <!-- BEGIN #footer-copyright -->
    {% block copyright %}
    <div id="footer-copyright" class="footer-copyright"">
        <!-- BEGIN container -->
        <div class="container">
            <div class="payment-method">
                <img src="assets/img/payment_method.png" alt=""/>
            </div>
            <div class="copyright">
                Copyright &copy; 2016 SeanTheme. All rights reserved.
            </div>
        </div>
        <!-- END container -->
    </div>
    {% endblock %}
    <!-- END #footer-copyright -->
</div>
<!-- END #page-container -->

<!-- begin theme-panel -->
<div class="theme-panel">
    <a href="javascript:;" data-click="theme-panel-expand" class="theme-collapse-btn"><i class="fa fa-cog"></i></a>
    <div class="theme-panel-content">
        <ul class="theme-list clearfix">
            <li><a href="javascript:;" class="bg-purple" data-theme="purple" data-click="theme-selector"
                   data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Purple">&nbsp;</a></li>
            <li><a href="javascript:;" class="bg-blue" data-theme="blue" data-click="theme-selector"
                   data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Blue">&nbsp;</a></li>
            <li class="active"><a href="javascript:;" class="bg-green" data-theme="default" data-click="theme-selector"
                                  data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Default">&nbsp;</a>
            </li>
            <li><a href="javascript:;" class="bg-orange" data-theme="orange" data-click="theme-selector"
                   data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Orange">&nbsp;</a></li>
            <li><a href="javascript:;" class="bg-red" data-theme="red" data-click="theme-selector" data-toggle="tooltip"
                   data-trigger="hover" data-container="body" data-title="Red">&nbsp;</a></li>
        </ul>
    </div>
</div>
<!-- end theme-panel -->

<!-- ================== BEGIN BASE JS ================== -->
<script src="{% static "assets/plugins/jquery/jquery-1.9.1.min.js" %}"></script>
<script src="{% static "assets/plugins/jquery/jquery-migrate-1.1.0.min.js" %}"></script>
<script src="{% static "assets/plugins/bootstrap/js/bootstrap.min.js" %}"></script>
<!--[if lt IE 9]>
		<script src="{% static "assets/crossbrowserjs/html5shiv.js" %}></script>
		<script src="{% static "assets/crossbrowserjs/respond.min.js" %}></script>
		<script src="{% static "assets/crossbrowserjs/excanvas.min.js" %}></script>
	<![endif]-->
<script src="{% static "assets/plugins/jquery-cookie/jquery.cookie.js" %}"></script>
<script src="{% static "assets/js/apps.min.js" %}"></script>
<!-- ================== END BASE JS ================== -->

<script>
    $(document).ready(function () {
        App.init();
    });
</script>
</body>
</html>